print( 'Ausgabe Kurve ohne Grafik' );
print( 3 * '*' );
print( 5 * '*' );
print( 8 * '*' );
print( 9 * '*' );
print( 10 * '*' );
print( 9 * '*' );
print( 8 * '*' );
print( 5 * '*' );
print( 3 * '*' );
