print( 'Ergebnis einer Umfrage' );
print( '======================' );
print( 'Antwort 1|', 3 * '*' );
print( 'Antwort 2|', 5 * '*' );
print( 'Antwort 3|', 7 * '*' );
print( 'Antwort 4|', 9 * '*' );
print( 'Antwort 5|', 10 * '*' );
print( 'Antwort 6|', 9 * '*' );
print( 'Antwort 7|', 7 * '*' );
print( 'Antwort 8|', 5 * '*' );
print( 'Antwort 9|', 3 * '*' );
